### ISSUE TITLE
Splunk OpenTelemetry Java Distribution - GA request

### ISSUE THREAD

**Issue by MrAlias** [signalfx/gdi-specification#106]
**Which GDI repository do you wish to GA?**

https://github.com/signalfx/splunk-otel-java

**Does the repository follow the latest tagged minor release in GDI specification?**

yes

**How long has the GDI repository been public?**

~8 months

**Is the repository known to be used today?**

yes

**Is there a date by which this approval is needed?**

2021-05-28

/cc @flands @mateuszrzeszutek

**Comment by mateuszrzeszutek** [comment]
> How long has the GDI repository been public?

~8 months?

**Comment by MrAlias** [comment]
# Configuration

## Splunk Specific Environment variables

- 🛑 `SPLUNK_ACCESS_TOKEN`
   - [ ] Listed as experimental instead of stable [in documentation](https://github.com/signalfx/splunk-otel-java/blob/b1a71602d411f53ed0bc9824e5fe2f6fe810e3de/docs/advanced-config.md).
- 🛑 `SPLUNK_TRACE_RESPONSE_HEADER_ENABLED`
   - [ ] Listed as experimental instead of stable [in documentation](https://github.com/signalfx/splunk-otel-java/blob/b1a71602d411f53ed0bc9824e5fe2f6fe810e3de/docs/advanced-config.md).
   - [ ] [Documented](https://github.com/signalfx/splunk-otel-java/blob/b1a71602d411f53ed0bc9824e5fe2f6fe810e3de/docs/advanced-config.md) to have a default value of `false` instead of `true`.

## OTel Environment Variables

- `OTEL_RESOURCE_ATTRIBUTES`
  - > User MUST define [`service.name`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service) resource attribute.

    ✅ Documented in [Getting Started](https://github.com/signalfx/splunk-otel-java#getting-started)
  - > Distribution MUST log a warning when the `service.name` resource attribute is not set.
    > The warning message MUST clearly describe how to set the attribute or link to relevant documentation.

    ✅ [It does](https://github.com/signalfx/splunk-otel-java/blob/f7a31b9a194ed731f5ed0ba2be7180cca3aef90f/custom/src/main/java/com/splunk/opentelemetry/ServiceNameChecker.java#L35-L40)
  - > User SHOULD define [`deployment.environment`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/deployment_environment.md#deployment) resource attribute.

    ✅ Documented in [Basic Configuration](https://github.com/signalfx/splunk-otel-java#basic-configuration)
  - > User SHOULD define [`service.version`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service)

    ✅ Documented in [Basic Configuration](https://github.com/signalfx/splunk-otel-java#basic-configuration)
- `OTEL_PROPAGATORS`
  - > Distribution MUST default to `"tracecontext,baggage"`

    ✅ Documented as such in [Advanced Configuration](https://github.com/signalfx/splunk-otel-java/blob/main/docs/advanced-config.md#trace-propagation-configuration), and linked to show this is the default in the OTel SDK.
  - > Distribution MUST support and document how to switch to `b3multi`

    ✅ Documented in [Advanced Configuration](https://github.com/signalfx/splunk-otel-java/blob/main/docs/advanced-config.md#trace-propagation-configuration)
- Span Collection Limits
  - > Distribution MUST default to `1000` for `OTEL_SPAN_LINK_COUNT_LIMIT` (not OpenTelemetry default)

    ✅ [Documented](https://github.com/signalfx/splunk-otel-java/blob/main/docs/advanced-config.md#trace-configuration) this way and [implementation verified](https://github.com/signalfx/splunk-otel-java/blob/a06487e8f826b99633f89269cde93fad2dd11e94/custom/src/main/java/com/splunk/opentelemetry/SplunkTracerProviderConfigurer.java#L32-L39).
  - > Distribution MUST be `unset` (unlimited) for all others (not OpenTelemetry default)

    ✅ [Documented](https://github.com/signalfx/splunk-otel-java/blob/main/docs/advanced-config.md#trace-configuration) this way and [implementation verified](https://github.com/signalfx/splunk-otel-java/blob/a06487e8f826b99633f89269cde93fad2dd11e94/custom/src/main/java/com/splunk/opentelemetry/SplunkTracerProviderConfigurer.java#L32-L39).
- Zipkin exporter
  - > Distribution MUST NOT list Zipkin exporter as supported (not supported by Smart Agent)

    ❓Only mention of Zipkin found in the [cloudfoundry buildpack](https://github.com/signalfx/splunk-otel-java/blob/b1a71602d411f53ed0bc9824e5fe2f6fe810e3de/deployments/cloudfoundry/buildpack/README.md). @mateuszrzeszutek can you verify this is not used in our distribution, but is for the buildpack itself?
- `OTEL_TRACES_EXPORTER`
  - > Distribution MUST default to `otlp`

    ✅ [Documented that way](https://github.com/signalfx/splunk-otel-java#splunk-distribution-of-opentelemetry-java)
  - > Distribution MUST offer `jaeger-thrift-splunk` that defaults to `http://127.0.0.1:9080/v1/trace`

    ✅ Documented that way in the [Advanced Config](https://github.com/signalfx/splunk-otel-java/blob/main/docs/advanced-config.md#trace-exporters)

## Environment variable alternatives

In addition to environment variables, other ways of defining configuration also exist:

- [Java System Properties](https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html):
  These properties MUST match the environment variables converting to lower case and replacing underscores with hyphens or periods.
   ✅ Documented that way in the [Advanced Config](https://github.com/signalfx/splunk-otel-java/blob/main/docs/advanced-config.md#trace-exporters)

**Comment by mateuszrzeszutek** [comment]
> @mateuszrzeszutek can you verify this is not used in our distribution, but is for the buildpack itself?

Yes, this is for the buildpack. It's also completely outdated and wrong, but it doesn't concern the javaagent 🤷‍♂️ 


> * 🛑 `SPLUNK_ACCESS_TOKEN`
>   
>   * [ ]  Listed as experimental instead of stable [in documentation](https://github.com/signalfx/splunk-otel-java/blob/b1a71602d411f53ed0bc9824e5fe2f6fe810e3de/docs/advanced-config.md).
> * 🛑 `SPLUNK_TRACE_RESPONSE_HEADER_ENABLED`
>   
>   * [ ]  Listed as experimental instead of stable [in documentation](https://github.com/signalfx/splunk-otel-java/blob/b1a71602d411f53ed0bc9824e5fe2f6fe810e3de/docs/advanced-config.md).

@flands weren't we going to mark those two as stable as a part of going 1.0?

**Comment by MrAlias** [comment]
# Semantic Conventions

## OpenTelemetry Resource Attributes

> - MUST set the following OpenTelemetry resource attributes according to the [OpenTelemetry Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions#telemetry-sdk):
>   - `telemetry.sdk.name`
>   - `telemetry.sdk.version`
>   - `telemetry.sdk.language`

✅ These are set by the default OTel SDK for a new resource (which is used to build the distribution one from):

https://github.com/open-telemetry/opentelemetry-java/blob/50408d499f85d5761d0a5ed9bf9d77d5ff01fff5/sdk/common/src/main/java/io/opentelemetry/sdk/resources/Resource.java#L53-L57

> - SHOULD set the following resource attributes when applicable:
>   - `telemetry.auto.version`

❓I'm not sure about this. I think this is done by the upstream auto-instrumenting agent, but I'm not able to verify. @mateuszrzeszutek can you verify this?

## Splunk Resource Attributes

> | Attribute  | Type | Description  | Examples  | Required |
> |---|---|---|---|---|
> | `splunk.distro.version` | string | The version number of the Splunk distribution being used. | `1.5.0` | Yes |

✅ https://github.com/signalfx/splunk-otel-java/blob/b1a71602d411f53ed0bc9824e5fe2f6fe810e3de/custom/src/main/java/com/splunk/opentelemetry/SplunkDistroVersionResourceProvider.java#L31-L51

**Comment by mateuszrzeszutek** [comment]
> ❓I'm not sure about this. I think this is done by the upstream auto-instrumenting agent, but I'm not able to verify. @mateuszrzeszutek can you verify this?

I can confirm that -- this is indeed done by the upstream agent.

**Comment by MrAlias** [comment]
# Repository

> Every GDI repository MUST adhere to the following specification before it can release a GA (`1.0.0`) release.
> GDI repositories MUST submit a GitHub issue on the GDI specification using the `Repository GA approval` type.
> Until the approval is granted, GDI repositories MUST NOT cut a GA release.

## Required Configuration

### Teams

> - MUST have a maintainers team
>   - MUST have `-maintainers` suffix
>   - MUST include at least two currently full-time Splunkers
>   - MUST NOT include any non-full-time Splunkers
> - SHOULD have an approvers team
>   - MUST have `-approvers` suffix

❓ @flands  to verify

### Permissions

> - MUST grant `Admin` [permission level](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization) to admins team
> - MUST grant `Maintain` [permission level](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization) to maintainers team
> - MUST grant `Write` [permission level](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization) to approvers team
> - MUST NOT grant `Write`, `Maintain`, `Admin` [permission level](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization) to any other user nor team
> - MUST NOT grant any permission (including `Read`) to any individual

❓ @flands  to verify

### Branch protection

> - MUST have a primary branch named `main`
> - MUST NOT allow anyone (including administrators) pushing directly to `main`
> - MUST require status checks to pass before merge to `main`
> - MUST require at least one CODEOWNER to approve a PR prior to merge
> - MUST require signed commits on `main`
> - MUST NOT allow merge commit (squash or rebase merging only)

❓ @flands  to verify

### Dependencies

> - MUST lock the versions of all build dependencies (e.g. libraries, binaries, scripts, docker images) or vendor them;
>   **EXCEPTION:** tools that are available out-of-the-box

✅ vendored with gradle.

> - MUST have Dependabot configured

[✅](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/.github/dependabot.yml)

### GitHub Actions

> - MUST use [GitHub secrets](https://docs.github.com/en/actions/reference/encrypted-secrets) to store sensitive data (auth tokens, passwords) and limit their usage to only required places
> - MUST NOT use [Personal Access Tokens](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token)
> - MUST [limit permissions of `GITHUB_TOKEN`](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token) when used
>   - MUST set [the repository's default permission](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository) to just read access for the `contents` scope.
>   - MUST only set the absolutely required `permissions` (least privilege)
>   - MUST set `permissions` for individual `jobs`

❓ @flands  to verify

### GitHub Applications

> - MUST have Jira GitHub App configured

❓ @flands  to verify

> - SHOULD have Codecov GitHub App configured

🚫 It does not seem to configured. IIRC this is intentional as it is hard to measure this for auto instrumentation.

> - SHOULD have Lychee Link Checker GitHub Action configured

🚫 It does not seem to configured. @mateuszrzeszutek can you verify?

## Required Files

> - MUST have a [CHANGELOG.md](templates/CHANGELOG.md) updated for every release
>   - The CHANGELOG.md is intended to be consumed by humans, and not machines.
>   - The file SHOULD contain an `Unreleased` section at the top, which includes changes that have not yet been released.
>   - The file MUST be in reverse chronological order, with the most recent releases at the top of the file, after the `Unreleased` section.
>   - Each release SHOULD be separated by a line separator (`---`) from the other relases.
>   - Each release SHOULD contain separate sections for each major functionality area (if applicable).
>     The following sub-sections MAY be used, as appropriate or specified.
>     - `General` - General comments about the release that users should know about.
>     - `Breaking Changes` - Any changes that will break backward compatibility with previous versions. MUST list all breaking changes.
>     - `Bugfixes` - Details of bugs that were fixed. SHOULD list all bug fixes.
>     - `Enhancements` - New features that have been added to the repository.
>       SHOULD list all new features.
>   - The CHANGELOG.md SHOULD NOT list every PR, but only changes significant from an end-user point of view.
>     Anyone who is interested in all the details of every change in the repository can use the git log for that.

✅ Conforming changelog found [here](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/CHANGELOG.md)

> - MUST add [CODE_OF_CONDUCT.md](templates/CODE_OF_CONDUCT.md)

✅ [here](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/CODE_OF_CONDUCT.md)

> - MUST add [CONTRIBUTING.md](templates/CONTRIBUTING.md)

✅ [here](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/CONTRIBUTING.md)

> - MUST have a [.github/CODEOWNERS](templates/.github/CODEOWNERS) file with a maintainers team

✅ [here](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/.github/CODEOWNERS)

> - SHOULD have an approvers team in CODEOWNERS

✅ [it does](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/.github/CODEOWNERS)

> - MUST have an Apache 2.0 `LICENSE` file

✅ [it does](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/LICENSE)

> - SHOULD have a `MIGRATING.md` if applicable

✅ [it does](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/MIGRATING.md)

> - MUST have a `README.md`

✅ [README](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/README.md)

>   - MUST have a badge on the `README.md` with build status

✅

>     - CI and PR builds and all tests/checks that are executed in them MUST be publicly accessible by anyone.

✅

>   - MUST have a badge on the `README.md` with GDI specification version supported

🛑 No, but this is a bit of a "chicken or the egg" situation. The GDI specification does not have a stable release yet.

>   - SHOULD have a badge on the `README.md` with code coverage, if appropriate.

🚫 N/A

>   - SHOULD have badges on the `README.md` for other relevant things including artifacts

✅

>   - MUST have getting started information in `README.md`

✅ [here](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/README.md#getting-started)

>   - MUST have troubleshooting information in `README.md`

✅ [troubleshooting doc](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/docs/troubleshooting.md) linked from README header.

>   - MUST have license information in `README.md`

✅ [here](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/README.md#license-and-versioning)

> - MAY have a `RELEASING.md` file that documents the release process, but this file MUST NOT document private processes.
>   For repositories that use private release jobs, the `RELEASING.md` file SHOULD be absent or, if included, just contain the following note:
>   > The release process involves signing built packages and binaries and thus
>   > must be kept private and not exposed publicly.

✅ [used to exist](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/RELEASING.md), but has been removed in `main`. This is optional.

> - MUST add the [SECURITY.md](templates/SECURITY.md)
>   - SHOULD add dependabot information to `SECURITY.md` if applicable

✅ [here](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/SECURITY.md)

> - SHOULD NOT contain comprehensive application examples.
>   Application examples showing multi-system interactions or even cross-language use cases SHOULD be put in the [Splunk OpenTelemetry example repository](https://github.com/signalfx/tracing-examples/tree/main/opentelemetry-tracing).
>   Smaller, developer focused, examples MAY be included in the repository if it is customary to do so for the coding language used.

✅ none found. External [examples](https://github.com/signalfx/tracing-examples/tree/main/opentelemetry-tracing/opentelemetry-java-tracing) linked to from README.

## GitHub Releases

> - MUST have a signature or a checksum with signature for all release artifacts
>   - SHOULD use Splunk signing key

❓ @flands  to verify

> - MUST use [signed tags](https://docs.github.com/en/github/authenticating-to-github/signing-tags)

❓ [v0.4.0](https://github.com/signalfx/splunk-otel-java/releases/tag/v0.4.0) and [v0.3.3](https://github.com/signalfx/splunk-otel-java/releases/tag/v0.3.3) tags are not signed. It looks as though all other tags are signed. @mateuszrzeszutek can you verify if the release process requires tags to be signed?

> - MUST state version of OpenTelemetry components built against if applicable

🛑 No, not that I could find. @mateuszrzeszutek did I miss this?

> - MUST update all examples in the [Splunk OpenTelemetry example repository](https://github.com/signalfx/tracing-examples/tree/main/opentelemetry-tracing) that depends on the repository to use the latest release.

❓ I'm not sure this is happening. [This](https://github.com/signalfx/tracing-examples/pull/70) updated the upstream OTel dependency, but I do not see use of this project in those examples yet. @mateuszrzeszutek can you confirm this?

## Instrumentation Libraries

> - MUST document all supported configuration parameters

✅ Documented in the [Advance Config](https://github.com/signalfx/splunk-otel-java/blob/v0.11.0/docs/advanced-config.md)

> - MUST document how to configure manual instrumentation

✅ [here](https://github.com/signalfx/splunk-otel-java#manually-instrument-a-java-application)

> - MUST document how to configure log correlation

🛑 Not found.

> - MUST define minimum supported version of each auto-instrumentation framework
>   - SHOULD define maximum supported version of each auto-instrumentation framework

🛑 Not found.

**Comment by flands** [comment]
* Teams: Confirmed
* Permissions: Confirmed though we have a bots group now with write @owais do this need to be a separate group or can we add to maintainers group? If required we may need spec update
* Branch permissions: Confirmed
* GitHub actions/applications: mine to verify confirmed

**Comment by mateuszrzeszutek** [comment]
> > * SHOULD have Codecov GitHub App configured
> 
> 🚫 It does not seem to configured. IIRC this is intentional as it is hard to measure this for auto instrumentation.

Yes, that's intentional.

> > * SHOULD have Lychee Link Checker GitHub Action configured
> 
> 🚫 It does not seem to configured. @mateuszrzeszutek can you verify?

I missed that one. I'll add it 👍 

> > * MUST use [signed tags](https://docs.github.com/en/github/authenticating-to-github/signing-tags)
> 
> ❓ [v0.4.0](https://github.com/signalfx/splunk-otel-java/releases/tag/v0.4.0) and [v0.3.3](https://github.com/signalfx/splunk-otel-java/releases/tag/v0.3.3) tags are not signed. It looks as though all other tags are signed. @mateuszrzeszutek can you verify if the release process requires tags to be signed?

I think that GH started to sign those tags automatically at some point (I do push signed tags from my machine though).
The release process does not verify this, but I believe that in its current state it doesn't have to: we still have a manual verification/upload step that must be done by a maintainer.

> > * MUST state version of OpenTelemetry components built against if applicable
> 
> 🛑 No, not that I could find. @mateuszrzeszutek did I miss this?

Every release states with OTel API/instrumentation it depends on, it's also explicitly mentioned in the [README](https://github.com/signalfx/splunk-otel-java/#manually-instrument-a-java-application):

> The Splunk Distribution of OpenTelemetry Java version 0.11.0 is compatible with:
> 
> * OpenTelemetry API version 1.2.0
> * OpenTelemetry Instrumentation for Java version 1.2.0
 
> > * MUST update all examples in the [Splunk OpenTelemetry example repository](https://github.com/signalfx/tracing-examples/tree/main/opentelemetry-tracing) that depends on the repository to use the latest release.
> 
> ❓ I'm not sure this is happening. [This](https://github.com/signalfx/tracing-examples/pull/70) updated the upstream OTel dependency, but I do not see use of this project in those examples yet. @mateuszrzeszutek can you confirm this?

We don't really have to update those examples manually in case of the javaagent: the start scripts/README instructions in each example app always download the latest javaagent version, e.g.:

```bash
# download the newest version of the agent
curl -sSL -o splunk-otel-javaagent-all.jar 'https://github.com/signalfx/signalfx-otel-java/releases/latest/download/splunk-otel-javaagent-all.jar'
```

> > * MUST document how to configure log correlation
> 
> 🛑 Not found.

https://github.com/signalfx/splunk-otel-java/#correlating-traces-with-logs
https://github.com/signalfx/splunk-otel-java/blob/main/docs/correlating-traces-with-logs.md

> > * MUST define minimum supported version of each auto-instrumentation framework
> >   
> >   * SHOULD define maximum supported version of each auto-instrumentation framework
> 
> 🛑 Not found.

We reference the upstream javaagent docs [here](https://github.com/signalfx/splunk-otel-java/blob/main/docs/supported-libraries.md) - the upstream repo contains [a list of all instrumented libs with their versions](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md#libraries--frameworks).

**Comment by mateuszrzeszutek** [comment]
> * 🛑 `SPLUNK_ACCESS_TOKEN`
>   
>   * [ ]  Listed as experimental instead of stable [in documentation](https://github.com/signalfx/splunk-otel-java/blob/b1a71602d411f53ed0bc9824e5fe2f6fe810e3de/docs/advanced-config.md).
>     
>     * [signalfx/splunk-otel-java#245](https://github.com/signalfx/splunk-otel-java/issues/245)
> * 🛑 `SPLUNK_TRACE_RESPONSE_HEADER_ENABLED`
>   
>   * [ ]  Listed as experimental instead of stable [in documentation](https://github.com/signalfx/splunk-otel-java/blob/b1a71602d411f53ed0bc9824e5fe2f6fe810e3de/docs/advanced-config.md).
>     
>     * [signalfx/splunk-otel-java#246](https://github.com/signalfx/splunk-otel-java/issues/246)
>   * [ ]  [Documented](https://github.com/signalfx/splunk-otel-java/blob/b1a71602d411f53ed0bc9824e5fe2f6fe810e3de/docs/advanced-config.md) to have a default value of `false` instead of `true`.
>     
>     * [signalfx/splunk-otel-java#247](https://github.com/signalfx/splunk-otel-java/issues/247)

https://github.com/signalfx/splunk-otel-java/pull/249

**Comment by MrAlias** [comment]
All issues have been resolved and the the splunk-otel-java project has been confirmed to be compliant with the 1.0.0 release of the GDI specification.
