### ISSUE TITLE
Splunk Opentelemetry Python GA request

### ISSUE THREAD

**Issue by owais** [signalfx/gdi-specification#113]
**Which GDI repository do you wish to GA?**
Splunk Distribution of OpenTelemetry Python
https://github.com/signalfx/splunk-otel-python

**Does the repository follow the latest tagged minor release in GDI specification?**
yes

**How long has the GDI repository been public?**
7-8 months

**Is the repository known to be used today?**
yes

**Is there a date by which this approval is needed?**
No

**Comment by owais** [comment]
@flands @MrAlias ^

**Comment by MrAlias** [comment]
# Configuration

> Any repository-specific configuration variable defined SHOULD be prefixed with `SPLUNK_` and MUST NOT be marked as stable unless added to the GDI specification.

- `SPLUNK_MAX_ATTR_LENGTH` is not documented or labeled experimental.

## Instrumentation Libraries

> It MUST be possible to configure an Instrumentation Library instance using the following
> environment variables:
>
> | Name (default value)                            | Description                                                    |
> | :------------------------------------:          | :--------------------------------------------------------:     |
> | `SPLUNK_ACCESS_TOKEN` ()                        | Access token added to exported data. [1]                       |
> | `SPLUNK_TRACE_RESPONSE_HEADER_ENABLED` (`true`) | Whether `Server-Timing` header is added to HTTP responses. [2] |
>
> - [1]: Not user required if another system performs the authentication. For
>   example, instrumentation libraries SHOULD send data to a locally running
>   agent. The agent MAY define the access token that is used. If the
>   instrumentation library is configured to send data directly to a Splunk
>   back-end then this variable MUST be defined. Even when sending to an agent,
>   instrumentation libraries MAY define this option (to support
>   [`access_token_passthrough`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/signalfxreceiver#configuration)).
>   This environment variable MUST work for `otlp` and `jaeger-thrift-splunk`
>   exporters.
> - [2]: If stitching of RUM spans and APM spans is desired then this parameter
>   MUST be set to `true`.

- ✅ Both look to be implemented according to specification.
    - [`SPLUNK_TRACE_RESPONSE_HEADER_ENABLED` (`true`)](https://github.com/signalfx/splunk-otel-python/blob/7b0cc8a40f7757b4cd411353811a7c85f9537f40/splunk_otel/options.py#L120)
    - [`SPLUNK_ACCESS_TOKEN` ()](https://github.com/signalfx/splunk-otel-python/blob/7b0cc8a40f7757b4cd411353811a7c85f9537f40/splunk_otel/options.py#L100)


> - `OTEL_RESOURCE_ATTRIBUTES`
>   - User MUST define [`service.name`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service)
>     resource attribute.

✅ [This test](https://github.com/signalfx/splunk-otel-python/blob/c27521005d3e85a2b0fcaa2013b39f4c860bc4c7/tests/unit/test_options.py#L47-L56) checks this is done.

>   - Distribution MUST log a warning when the `service.name` resource attribute is not set. The
>     warning message MUST clearly describe how to set the attribute or link to relevant documentation.
>     E.g.
>     ```
>     service.name attribute is not set, your service is unnamed and will be difficult to identify.
>     set your service name using the OTEL_RESOURCE_ATTRIBUTES environment variable.
>     E.g. `OTEL_RESOURCE_ATTRIBUTES="service.name=<YOUR_SERVICE_NAME_HERE>"`
>     ```

✅ Logged [here](https://github.com/signalfx/splunk-otel-python/blob/ce814b576b287bf57c312fdf0d6e2488961f1dd1/splunk_otel/options.py#L145)

> - `OTEL_PROPAGATORS`
>   - Distribution MUST default to `"tracecontext,baggage"`

✅ Tested [here](https://github.com/signalfx/splunk-otel-python/blob/c27521005d3e85a2b0fcaa2013b39f4c860bc4c7/tests/unit/test_propagation.py#L32-L40)

>   - Distribution MUST support and document how to switch to `b3multi`

✅ Done [here](https://github.com/signalfx/splunk-otel-python/blob/a9f9e6191b1393a84a54e257978bd7b9f74fbb22/docs/configuring-propagators.md#configuring-b3-propagator)

> - Span Collection Limits
>   - Distribution MUST default to `1000` for `OTEL_SPAN_LINK_COUNT_LIMIT` (not OpenTelemetry default)

✅ Done [here](https://github.com/signalfx/splunk-otel-python/blob/ce814b576b287bf57c312fdf0d6e2488961f1dd1/splunk_otel/options.py#L188)

>   - Distribution MUST be `unset` (unlimited) for all others (not OpenTelemetry default)

✅ Done [here](https://github.com/signalfx/splunk-otel-python/blob/ce814b576b287bf57c312fdf0d6e2488961f1dd1/splunk_otel/options.py#L183-L187)

> - Zipkin exporter
>   - Distribution MUST NOT list Zipkin exporter as supported (not supported by Smart Agent)

✅ Grep-ing shows Zipkin is only mentioned in [lint configuration](https://github.com/signalfx/splunk-otel-python/blob/53d69c39305b58d343c38acb01869cf1e6bbf29f/.pylintrc#L173)

> - `OTEL_TRACES_EXPORTER`
>   - Distribution MUST default to `otlp`

✅ [here](https://github.com/signalfx/splunk-otel-python/blob/ce814b576b287bf57c312fdf0d6e2488961f1dd1/splunk_otel/symbols.py#L16)

>   - Distribution MUST offer `jaeger-thrift-splunk` that defaults to `http://127.0.0.1:9080/v1/trace`

✅ [Documentation](https://github.com/signalfx/splunk-otel-python/blob/a9f9e6191b1393a84a54e257978bd7b9f74fbb22/docs/exporting-data.md#to-signalfx-smart-agent)
✅ [Endpoint](https://github.com/signalfx/splunk-otel-python/blob/ce814b576b287bf57c312fdf0d6e2488961f1dd1/splunk_otel/symbols.py#L17)

**Comment by MrAlias** [comment]
# Repository

### Teams

> - MUST have a maintainers team
>   - MUST have `-maintainers` suffix
>   - MUST include at least two currently full-time Splunkers
>   - MUST NOT include any non-full-time Splunkers

✅ https://github.com/orgs/signalfx/teams/gdi-python-maintainers

> - SHOULD have an approvers team
>   - MUST have `-approvers` suffix

✅ https://github.com/orgs/signalfx/teams/gdi-python-approvers


### Permissions

> - MUST grant `Admin` [permission
>   level](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization)
>   to admins team
> - MUST grant `Maintain` [permission
>   level](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization)
>   to maintainers team
> - MUST grant `Write` [permission
>   level](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization)
>   to approvers team
> - MUST NOT grant `Write`, `Maintain`, `Admin` [permission
>   level](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization)
>   to any other user nor team
> - MUST NOT grant any permission (including `Read`) to any individual

❓ I do not have permissions to verify. @flands or @owais please verify.

### Branch protection

> - MUST have a primary branch named `main`
> - MUST NOT allow anyone (including administrators) pushing directly to `main`
> - MUST require status checks to pass before merge to `main`
> - MUST require at least one CODEOWNER to approve a PR prior to merge
> - MUST require signed commits on `main`
> - MUST NOT allow merge commit (squash or rebase merging only)

❓ I do not have permissions to verify. @flands or @owais please verify.

### GitHub Actions

> - MUST use [GitHub
>   secrets](https://docs.github.com/en/actions/reference/encrypted-secrets) to
>   store sensitive data (auth tokens, passwords) and limit their usage to only
>   required places
> - MUST NOT use [Personal Access
>   Tokens](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token)
> - MUST [limit permissions of
>   `GITHUB_TOKEN`](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token)
>   when used
>   - MUST set [the repository's default permission](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository)
>     to just read access for the `contents` scope.
>   - MUST only set the absolutely required `permissions` (least privilege)
>   - MUST set `permissions` for individual `jobs`

❓ It doesn't look like there are any actions enabled, but I do not have permissions to verify. @flands or @owais please verify.

### GitHub Applications

> - MUST have Jira GitHub App configured

🛑 This does not look configured. @owais can you confirm this please?

> - SHOULD have Codecov GitHub App configured
> - SHOULD have Lychee Link Checker GitHub Action configured

❗ I do not see any of these configured.

## Required Files

> - MUST have a [CHANGELOG.md](templates/CHANGELOG.md) updated for every release

✅ [here]([https://github.com/signalfx/splunk-otel-python/blob/v1.0.0rc4/CHANGELOG.md)

>   - The file SHOULD contain an `Unreleased` section at the top, which includes changes that
>   have not yet been released.

✅ It does.

>   - The file MUST be in reverse chronological order, with the most recent
>   releases at the top of the file, after the `Unreleased` section.

🛑 Missing entry for 1.0.0rc4

>   - Each release SHOULD be separated by a line separator (`---`) from the other relases.
>   - Each release SHOULD contain separate sections for each major functionality area (if applicable).
>   The following sub-sections MAY be used, as appropriate or specified.
>     - `General` - General comments about the release that users should know about.
>     - `Breaking Changes` - Any changes that will break backward compatibility
>       with previous versions. MUST list all breaking changes.
>     - `Bugfixes` - Details of bugs that were fixed. SHOULD list all bug fixes.
>     - `Enhancements` - New features that have been added to the repository. SHOULD
>       list all new features.
>   - The CHANGELOG.md SHOULD NOT list every PR, but only changes significant
>     from an end-user point of view. Anyone who is interested in all the details
>     of every change in the repository can use the git log for that.

❗ It looks like the CHANGELOG format matches [keepachangelog](https://keepachangelog.com/en/1.0.0/) not the GDI specified format.

> - MUST add [CODE_OF_CONDUCT.md](templates/CODE_OF_CONDUCT.md)

🛑 Missing CODE_OF_CONDUCT.md

> - MUST add [CONTRIBUTING.md](templates/CONTRIBUTING.md)

✅ [here](https://github.com/signalfx/splunk-otel-python/blob/v1.0.0rc4/CONTRIBUTING.md)

> - MUST have a [.github/CODEOWNERS](templates/.github/CODEOWNERS) file with a maintainers team
> - SHOULD have an approvers team in CODEOWNERS

🛑 [CODEOWNERS file](https://github.com/signalfx/splunk-otel-python/blob/v1.0.0rc4/CODEOWNERS) only lists @owais, not a maintainers team.

> - MUST have an Apache 2.0 `LICENSE` file

✅ [here](https://github.com/signalfx/splunk-otel-python/blob/v1.0.0rc4/LICENSE)

> - SHOULD have a `MIGRATING.md` if applicable

✅ [here](https://github.com/signalfx/splunk-otel-python/blob/v1.0.0rc4/MIGRATING.md)

> - MUST have a `README.md`

✅ [here](https://github.com/signalfx/splunk-otel-python/blob/v1.0.0rc4/README.md)

>   - MUST have a badge on the `README.md` with build status
>     - CI and PR builds and all tests/checks that are executed in them MUST be
>       publicly accessible by anyone.

❓ @owais can you verify the CircleCI build system is publicly accessible?

>   - MUST have a badge on the `README.md` with GDI specification version supported

🛑 this is missing.

>   - SHOULD have a badge on the `README.md` with code coverage, if appropriate.

✅

>   - SHOULD have badges on the `README.md` for other relevant things including artifacts

✅

>   - MUST have getting started information in `README.md`

✅ [here](https://github.com/signalfx/splunk-otel-python/blob/v1.0.0rc4/README.md#getting-started)

>   - MUST have troubleshooting information in `README.md`

✅ Linked in README header to troubleshooting doc.

>   - MUST have license information in `README.md`

✅ [here](https://github.com/signalfx/splunk-otel-python/blob/v1.0.0rc4/README.md#license-and-versioning)

> - MAY have a `RELEASING.md` file that documents the release process, but this
>   file MUST NOT document private processes. For repositories that use private release
>   jobs, the `RELEASING.md` file SHOULD be absent or, if included, just contain the following note:
>   > The release process involves signing built packages and binaries and thus
>   > must be kept private and not exposed publicly.

✅ [here](https://github.com/signalfx/splunk-otel-python/blob/v1.0.0rc4/RELEASING.md), it does not look to included a private process.

> - MUST add the [SECURITY.md](templates/SECURITY.md)
>   - SHOULD add dependabot information to `SECURITY.md` if applicable

✅ [here](https://github.com/signalfx/splunk-otel-python/blob/v1.0.0rc4/SECURITY.md)

> - SHOULD NOT contain comprehensive application examples. Application examples
>   showing multi-system interactions or even cross-language use cases SHOULD be
>   put in the [Splunk OpenTelemetry example
>   repository](https://github.com/signalfx/tracing-examples/tree/main/opentelemetry-tracing).
>   Smaller, developer focused, examples MAY be included in the repository if it
>   is customary to do so for the coding language used.

✅ [Smaller developer oriented example here](https://github.com/signalfx/splunk-otel-python/tree/v1.0.0rc4/examples/falcon)

## GitHub Releases

> - MUST have a signature or a checksum with signature for all release artifacts
>   - SHOULD use Splunk signing key

❓ @owais can you confirm this please?

> - MUST use [signed tags](https://docs.github.com/en/github/authenticating-to-github/signing-tags)

✅ [All tags look verified](https://github.com/signalfx/splunk-otel-python/tags)

> - MUST state version of OpenTelemetry components built against if applicable

✅ [1.0.0rc4 does](https://github.com/signalfx/splunk-otel-python/releases/tag/v1.0.0rc4)

> - MUST update all examples in the [Splunk OpenTelemetry example
>   repository](https://github.com/signalfx/tracing-examples/tree/main/opentelemetry-tracing)
>   that depends on the repository to use the latest release.

🛑

- https://github.com/signalfx/tracing-examples/blob/8625b34883e86b35d784406847698404aaa27be9/opentelemetry-tracing/opentelemetry-python-tracing/django-and-gunicorn/requirements.txt#L14
- https://github.com/signalfx/tracing-examples/blob/8625b34883e86b35d784406847698404aaa27be9/opentelemetry-tracing/opentelemetry-python-tracing/flask-and-gunicorn/requirements.txt#L21
- https://github.com/signalfx/tracing-examples/blob/8625b34883e86b35d784406847698404aaa27be9/opentelemetry-tracing/opentelemetry-python-tracing/flask-and-uswgi/requirements.txt#L15

## Instrumentation Libraries

> - MUST document all supported configuration parameters

🛑

- `OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT`, `OTEL_SPAN_EVENT_COUNT_LIMIT`, and `OTEL_SPAN_LINK_COUNT_LIMIT` look undocumented (different default value from OTel). I'm not 100% sure this is required to be documented though.
- `SPLUNK_MAX_ATTR_LENGTH` looks undocumented. @owais please confirm.

> - MUST document how to configure manual instrumentation

✅ [here](https://github.com/signalfx/splunk-otel-python/tree/v1.0.0rc4#manually-instrument-an-application)

> - MUST document how to configure log correlation

✅ [here](https://github.com/signalfx/splunk-otel-python/tree/v1.0.0rc4#correlating-traces-with-logs)

> - MUST define minimum supported version of each auto-instrumentation framework
>   - SHOULD define maximum supported version of each auto-instrumentation framework

❓ There are docs on [some frameworks](https://github.com/signalfx/splunk-otel-python/blob/v1.0.0rc4/docs/instrumentation-special-cases.md), but I do not see a list of versions.  @owais can you confirm this please, or state its applicability?

**Comment by MrAlias** [comment]
# Semantic Conventions

## OpenTelemetry Resource Attributes

> - MUST set the following OpenTelemetry resource attributes according to the [OpenTelemetry Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions#telemetry-sdk):
>   - `telemetry.sdk.name`
>   - `telemetry.sdk.version`
>   - `telemetry.sdk.language`

🛑 Looks to be missing. @owais can you confirm this?

> - SHOULD set the following resource attributes when applicable:
>   - `telemetry.auto.version`

✅ [set here](https://github.com/signalfx/splunk-otel-python/blob/ce814b576b287bf57c312fdf0d6e2488961f1dd1/splunk_otel/options.py#L136)


## Splunk Resource Attributes

> | Attribute  | Type | Description  | Examples  | Required |
> |---|---|---|---|---|
> | `splunk.distro.version` | string | The version number of the Splunk distribution being used. | `1.5.0` | Yes |

✅ [set here](https://github.com/signalfx/splunk-otel-python/blob/ce814b576b287bf57c312fdf0d6e2488961f1dd1/splunk_otel/options.py#L137)

**Comment by MrAlias** [comment]
# Versioning

> All GDI components MUST be versioned according to [Semantic Versioning
> 2.0](https://semver.org/spec/v2.0.0.html).

✅ [looks so](https://github.com/signalfx/splunk-otel-python/tags)

> GDI components MUST indicate what version of OpenTelemetry components they are based on through release notes and SHOULD indicate through logging.

✅ [looks so](https://github.com/signalfx/splunk-otel-python/releases/tag/v1.0.0rc4)

## Experimental

> GDI repositories MAY consist of one or more components. GDI repositories MUST be
> designed in a manner that allows experimental components to be created without
> breaking the stability guarantees of existing components. GDI repositories MUST NOT
> be designed in a manner that breaks existing users when a new component beyond
> the repository's first component transitions from experimental to stable. This
> would punish users of the release candidate component, and hinder adoption.

❓ I am not qualified to answer this. @owais can you confirm this is satisfied?

> Terms which denote stability, such as `experimental` MUST NOT be used as part
> of a directory or import name. Package version numbers MAY include a suffix,
> such as `-alpha`, `-beta`, `-rc`, or `-experimental`, to differentiate stable
> and experimental components.

✅ Currently this is not done.

**Comment by flands** [comment]
* Permissions: ✅ Confirmed, done
* CODEOWNERS: 🛑 Not correct, not enforced on branch @owais please fix then I can set
* GitHub actions: ✅ LGTM

**Comment by owais** [comment]
> 🛑 Looks to be missing. @owais can you confirm this?


- [x] This is handled by Otel SDK out of the box:
https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py#L168
https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py#L246-L252


> CODEOWNERS: 🛑 Not correct, not enforced on branch @owais please fix then I can set

- [x] Fixed.

>>    GDI repositories MAY consist of one or more components. GDI repositories MUST be
>>    designed in a manner that allows experimental components to be created without
>>    breaking the stability guarantees of existing components. GDI repositories MUST NOT
>>    be designed in a manner that breaks existing users when a new component beyond
>>    the repository's first component transitions from experimental to stable. This
>>    would punish users of the release candidate component, and hinder adoption.

> ❓ I am not qualified to answer this. @owais can you confirm this is satisfied?

- [x] I don't think we do anything that violates this principle. Python allows us to structure the repo however we change and completely change that structure without affecting stable packages. We can add/remove more stable/beta packages in future easily.


> >  MUST define minimum supported version of each auto-instrumentation framework
>>   SHOULD define maximum supported version of each auto-instrumentation framework

> ❓ There are docs on some frameworks, but I do not see a list of versions. @owais can you confirm this please, or state its applicability?

[ ] We don't document this today in Splunk repo. I'll take care of this. 

> MUST have a signature or a checksum with signature for all release artifacts
>  SHOULD use Splunk signing key

- [x] We publish checksums of published packages to checksums.txt for each release. https://github.com/signalfx/splunk-otel-python/releases/tag/v0.17.0


>    OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT, OTEL_SPAN_EVENT_COUNT_LIMIT, and OTEL_SPAN_LINK_COUNT_LIMIT look undocumented (different default value from OTel). I'm not 100% sure this is required to be documented though.
    SPLUNK_MAX_ATTR_LENGTH looks undocumented. @owais please confirm.

- [ ] pending documentation


>  MUST have a badge on the README.md with GDI specification version supported

- [x] Fixed


> 🛑 Missing entry for 1.0.0rc4

- [ ] This is a pre-release package and wasn't merged into the main branch. It lives in its own release branch. I'll copy the changelog bits for convenience.




> MUST update all examples in the Splunk OpenTelemetry example repository that depends on the repository to use the latest release.

- [ ] pending 

> 🛑 Missing CODE_OF_CONDUCT.md

- [x] added


>  SHOULD have Codecov GitHub App configured
> SHOULD have Lychee Link Checker GitHub Action configured

- [x] codecov was already enabled and I've enabled lychee as well.


> ❗ It looks like the CHANGELOG format matches keepachangelog not the GDI specified format.

- [ ] We are using tooling built around keepachagelog that helps us automate releases. I'll see if the tools we use works with GDI format. 


> 🛑 This does not look configured. @owais can you confirm this please?
- [x] Configured by @flands

**Comment by owais** [comment]
@MrAlias I think I've taken care of or answered all questions. I'll go over this once more tomorrow and make sure I didn't miss anything but please feel free to review.

**Comment by owais** [comment]
@MrAlias @flands PTAL. Thanks

**Comment by MrAlias** [comment]
Sorry about the delay,

- @flands can you double check the branch protections now that the CODEOWNERS is compliant?
- @owais can you confirm the Jira GitHub app is configured? (sorry if I missed that it was already addressed)

Otherwise, this all looks good to me :+1:

**Comment by owais** [comment]
@flands confirmed on slack a couple of weeks ago that he configured the JIRA GitHub app. I'm not sure how to configure or even test it :) 

@flands can you answer both please? ^

**Comment by flands** [comment]
Both done and confirmed!

**Comment by MrAlias** [comment]
All issues have been resolved and the the splunk-otel-python project has been confirmed to be compliant with the 1.0.0 release of the GDI specification.
