### ISSUE TITLE
signalfx/docs need WRITE permission in every repo

### ISSUE THREAD

**Issue by mateuszrzeszutek** [signalfx/gdi-specification#118]
Related to #115 and #117

We've added the `signalfx/docs` team as an approver to every repo, that means that we've got to grant that team WRITE permission to every GDI repo. Is this okay? Should we add that requirement to `repository.md`? Or should we resurrect the approach from https://github.com/signalfx/gdi-specification/pull/88 (GHA that adds reviewers)?

**Comment by pellared** [comment]
We already agreed that approvers have WRITE/. Therefore I would do the same for `signalfx/docs` team.
