### ISSUE TITLE
SignalFx Lambda Extension Layer - GA request

### ISSUE THREAD

**Issue by kubawach** [signalfx/gdi-specification#122]
Which GDI project do you wish to GA?
https://github.com/signalfx/signalfx-extension-wrapper

Does the repository follow the latest tagged minor release in GDI specification?
yes

How long has the GDI project been public?
None

Is the project known to be used today?
Yes

Is there a date by which this approval is needed?
No

Additional context
Build / release in GitLab

**Comment by pellared** [comment]
@mzajacsplunk Can we close this one?

**Comment by pellared** [comment]
@johnbley

**Comment by johnbley** [comment]
The signalfx-extension-wrapper repo is still in active use, though indirectly through the (private) lambda-layers one.  The long-term usage of this component is unclear at the moment.  We have no specific plans to work towards GA/1.0/GDI-spec-compliance of signalfx-extension-wrapper at the moment.
