### ISSUE TITLE
Repository / Teams

### ISSUE THREAD

**Issue by kubawach** [signalfx/gdi-specification#123]
Currently the spec says:
```
MUST have a maintainers team
MUST have -maintainers suffix
MUST include at least two currently full-time Splunkers
MUST NOT include any non-full-time Splunkers
SHOULD have an approvers team
MUST have -approvers suffix
```

The question is whether it means that there should be a single (approver / maintainer) team per repo or rather that each repo has to have a team assigned and teams can be shared between repos? The rationale behind the latter is that we have multiple teams from eg Java domain that should (and actually do) share maintainers / approvers.

@pellared @iNikem ^^ out of our recent discussion

**Comment by pellared** [comment]
For me: 

```
Each repo MUST have a team assigned and teams MAY BE shared between repositories.
```

Otherwise, it won't give a lot of benefits especially that AFAIK you cannot add one team to another team in GitHub...

**Comment by kubawach** [comment]
Cool, I'll put it into spec then :)
