### ISSUE TITLE
Specify export protocol

### ISSUE THREAD

**Issue by Rauno56** [signalfx/gdi-specification#131]
**Is your feature request related to a problem? Please describe.**
We currently spec the distros to use OTLP, but are not saying whether the protocol should be over HTTP or gRPC. The latest version of the Collector receives those on different ports. There has been an [effort to consolidate that](https://github.com/open-telemetry/opentelemetry-collector/pull/3765).
Would we want to spec that?

**Describe the solution you'd like**
Since our ingest only supports OTLP/HTTP it makes sense to prefer that over gRPC and default to 4318. Otherwise, we'd need to provide additional configuration and complexity to switch between collectorless and "collectorful" usecases.

**Describe alternatives you've considered**
An alternative would be to default to OTLP/gRPC(currently on port 4317 on the Collector), which is what Python and Java does, but that means additional configuration burden when switching to collectorless setup.

**Comment by pellared** [comment]
> Would we want to spec that?

Yes 👍 It would avoid confusion whatever we agree on.

**Comment by pellared** [comment]
@Rauno56 Can I assign this issue to you?

**Comment by Rauno56** [comment]
Solved in https://github.com/signalfx/gdi-specification/pull/132!
