### ISSUE TITLE
Support `SPLUNK_REALM` in instrumentation libraries

### ISSUE THREAD

**Issue by mateuszrzeszutek** [signalfx/gdi-specification#140]
**Is your feature request related to a problem? Please describe.**
Right now the "standard" instrumentation libraries do not support the `SPLUNK_REALM` configuration setting; it is supported by RUM & serverless libraries and the collector though.

We could introduce that setting to all instrumentation libraries; it could work in the following way:
* if `SPLUNK_REALM` is specified, the exporter endpoint will point to the ingest;
* if `SPLUNK_REALM` and the exporter endpoint config variable are both specified, the exporter setting takes precedence;
* when `SPLUNK_REALM` and exporter endpoint are not specified, the default endpoint values (pointing to collector) will be used.

**Comment by pellared** [comment]
@owais WDYT of `none` instead of `local`? Just to have similarity to `OTEL_PROPAGATORS` and `OTEL_*_EXPORTER`.

Reference: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md
