### ISSUE TITLE
GA request - Splunk Distribution of OpenTelemetry Go

### ISSUE THREAD

**Issue by pellared** [signalfx/gdi-specification#173]
**Which GDI repository do you wish to GA?**

[Splunk Distribution of OpenTelemetry Go](https://github.com/signalfx/splunk-otel-go)

**Does the repository follow the latest tagged minor release in [GDI specification](../../specification/repository.md)?**

  - [x] Has an appropriate [maintainers team](../../specification/repository.md#teams).
  - [x] [Permissions](../../specification/repository.md#permissions) set correctly.
  - [x] [Branch protection](../../specification/repository.md#branch-protection) in place.
  - [x] [Dependencies](../../specification/repository.md#dependencies) appropriately locked down.
  - [x] [GitHub Applications](../../specification/repository.md#github-applications) set up per spec. 
  - [x] Follows the [configuration requirements](../../specification/configuration.md), if appropriate.
  - [x] Follows the [semantic convention requirements](../../specification/semantic_conventions.md), if appropriate.
  - [x] [Required Files](../../specification/repository.md#required-files) in place.
    - [x] CHANGELOG.md
    - [x] CODE_OF_CONDUCT.md
    - [x] CONTRIBUTING.md
    - [x] .github/CODEOWNERS
    - [x] LICENSE
    - [x] README.md
      - [x] Build status badge
      - [x] Getting started
      - [x] Troubleshooting
      - [x] Link to official Splunk docs
      - [x] License information
    - [x] SECURITY.md
  - [x] [Releases](../../specification/repository.md#github-releases) done to spec.
  - [x] Type specific requirements (remove what doesn't apply)
    - [x] [Instrumentation Library](../../specification/repository.md#instrumentation-libraries)
      - [x] Documents all supported configuration parameters.
      - [x] Documents how to configure manual instrumentation.
      - [x] Documents how to configure log correlation.
      - [x] Documents minimum supported version of each auto-instrumentation framework.
    - [x] [Real User Monitoring Library](../../specification/repository.md#real-user-monitoring-libraries)
      - [x] Documents all supported configuration parameters.
      - [x] Documents how to configure manual instrumentation.
      - [x] Documents supported instrumentation.
      - [x] Documents supported platforms.

**How long has the GDI repository been public?**

About a year

**Is the repository known to be used today?**

Yes

**Is there a date by which this approval is needed?**

June 10 2022, to announce it during [Splunk .conf22](https://conf.splunk.com/)

**Additional context**

**Comment by pellared** [comment]
Together with @mzajacsplunk we have checked and updated the repository setting to meet the GDI specification.

**Comment by pellared** [comment]
@MrAlias Can you double-check everything? It looks like Splunk OTel Go meets the GDI spec.

**Comment by MrAlias** [comment]
README badge needs to be reflect the v1.3.0 version of the GDI spec it will be compliant with: https://github.com/signalfx/splunk-otel-go/pull/993

**Comment by MrAlias** [comment]
> - MUST have a README.md
>   - MUST have getting started information in README.md
>   - MUST have troubleshooting information in README.md

[This](https://github.com/signalfx/gdi-specification/blob/main/specification/repository.md#required-files) is missing from the top level README.

**Comment by MrAlias** [comment]
Validated conforms to [configuration](https://github.com/signalfx/gdi-specification/blob/main/specification/configuration.md) specification

**Comment by MrAlias** [comment]
> > * MUST have a README.md
> >   
> >   * MUST have getting started information in README.md
> >   * MUST have troubleshooting information in README.md
> 
> [This](https://github.com/signalfx/gdi-specification/blob/main/specification/repository.md#required-files) is missing from the top level README.

I'm making a PR to address this.

**Comment by MrAlias** [comment]
https://github.com/signalfx/splunk-otel-go/pull/994

**Comment by MrAlias** [comment]
> [signalfx/splunk-otel-go#994](https://github.com/signalfx/splunk-otel-go/pull/994)

Merged.

With that, that splunk-otel-go repository has been validated to comply with the v1.3.0 version of the GDI specification :tada:.
