### ISSUE TITLE
GA requirements for dependency version pinning is unclear

### ISSUE THREAD

**Issue by breedx-splk** [signalfx/gdi-specification#179]
In this section of the GA requirements: https://github.com/signalfx/gdi-specification/blob/4d4cdfab21ae690e7b48aef8e1c5040ce80ed14b/specification/repository.md#dependencies it says:

> MUST lock the versions of all build dependencies (e.g. libraries, binaries, scripts, docker images) or vendor them; EXCEPTION: tools that are available out-of-the-box

I think that the "out-of-the-box" portion is too vague -- aren't all dependencies really "out-of-the-box"? If not, what does this even mean?

Does the pinning requirement apply to dependencies used in tests/testing?

**Comment by pellared** [comment]
> I think that the "out-of-the-box" portion is too vague -- aren't all dependencies really "out-of-the-box"? If not, what does this even mean?

I see "out-of-the-box" as the tools already installed on the CI runners

> Does the pinning requirement apply to dependencies used in tests/testing?

Currently, yes.
