### ISSUE TITLE
GA splunk-otel-android

### ISSUE THREAD

**Issue by breedx-splk** [signalfx/gdi-specification#182]
Note: This could be understood as a continuation of #133.

I have done front-loaded a lot of evidence toward this GA effort in https://signalfuse.atlassian.net/browse/APMI-3264.

### Which GDI repository do you wish to GA?
[splunk-otel-android](https://github.com/signalfx/splunk-otel-android)

### Does the repository follow the latest tagged minor release in [GDI specification](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md)?

- [x] Has an appropriate [maintainers team](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#teams).
- [x] [Permissions](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#permissions) set correctly.
- [x] [Branch protection](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#branch-protection) in place.
- [x] [Dependencies](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#dependencies) appropriately locked down.
- [x] [GitHub Applications](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#github-applications) set up per spec. 
- [x] Follows the [configuration requirements](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/configuration.md), if appropriate.
- [x] Follows the [semantic convention requirements](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/semantic_conventions.md), if appropriate.
- [x] [Required Files](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#required-files) in place.
  - [x] CHANGELOG.md
  - [x] CODE_OF_CONDUCT.md
  - [x] CONTRIBUTING.md
  - [x] .github/CODEOWNERS
  - [x] LICENSE
  - [x] README.md
    - [x] Build status badge
    - [x] Getting started
    - [x] Troubleshooting
    - [x] Link to official Splunk docs
    - [x] License information
  - [x] SECURITY.md
- [x] [Releases](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#github-releases) done to spec.
- [x] Type specific requirements (remove what doesn't apply)
  - [x] [Real User Monitoring Library](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#real-user-monitoring-libraries)
    - [x] Documents all supported configuration parameters.
    - [x] Documents how to configure manual instrumentation.
    - [x] Documents supported instrumentation.
    - [x] Documents supported platforms.

### How long has the GDI repository been public?

At least [411 days](https://github.com/signalfx/splunk-otel-android/releases/tag/v0.1.0).

### Is the repository known to be used today?

YES. 

### Is there a date by which this approval is needed?**

No.

### Additional context

The Splunk Android SDK supports the RUM product and has not undergone significant destabilizing changes in many many months. It has been used in production by customers for months, and we believe that it is compliant with the latest GDI specification. We are intending to donate the code in this SDK to the OpenTelemetry community.

**Comment by mateuszrzeszutek** [comment]
I believe that somebody other than the Java team folks should take a look at it - ping @signalfx/gdi-specification-maintainers

**Comment by pellared** [comment]
I will take it. I will probably start working on it next week,

**Comment by pellared** [comment]
These are the only issues I have found

- https://github.com/signalfx/splunk-otel-android/issues/343
- https://github.com/signalfx/splunk-otel-android/issues/345

This is really great 👏

**Comment by pellared** [comment]
I certify that meets [v1.4.0](https://github.com/signalfx/gdi-specification/tree/v1.4.0) of the GDI Spec.

I guess it is time to remove the "BETA" notice and publish a `v1.0.0` release of https://github.com/signalfx/splunk-otel-android

**Comment by MrAlias** [comment]
> I certify that `splunk-otel-android` meets [v1.4.0](https://github.com/signalfx/gdi-specification/tree/v1.4.0) of the GDI Spec.
> 
> I guess it is time to remove the "BETA" notice and publish a `v1.0.0` release of https://github.com/signalfx/splunk-otel-android
