### ISSUE TITLE
GA splunk-otel-ruby

### ISSUE THREAD

**Issue by tsloughter-splunk** [signalfx/gdi-specification#183]
### Which GDI repository do you wish to GA?

[splunk-otel-ruby](https://github.com/signalfx/splunk-otel-ruby/)

### Does the repository follow the latest tagged minor release in [GDI specification](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md)?

- [x] Has an appropriate [maintainers team](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#teams).
- [x] [Permissions](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#permissions) set correctly.
- [x] [Branch protection](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#branch-protection) in place.
- [ ] [Dependencies](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#dependencies) appropriately locked down.
- [ ] [GitHub Applications](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#github-applications) set up per spec. 
- [ ] Follows the [configuration requirements](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/configuration.md), if appropriate.
- [x] Follows the [semantic convention requirements](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/semantic_conventions.md), if appropriate.
- [x] [Required Files](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#required-files) in place.
  - [x] CHANGELOG.md
  - [x] CODE_OF_CONDUCT.md
  - [x] CONTRIBUTING.md
  - [x] .github/CODEOWNERS
  - [x] LICENSE
  - [ ] README.md
    - [x] Build status badge
    - [x] Getting started
    - [x] Troubleshooting
    - [ ] Link to official Splunk docs
    - [x] License information
  - [x] SECURITY.md
- [ ] [Releases](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#github-releases) done to spec.
- [x] Type specific requirements (remove what doesn't apply)
  - [x] [Data Collector](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#data-collector)
    - [x] Documents all supported configuration parameters.
    - [x] Documents sizing guidelines
  - [ ] [Instrumentation Library](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#instrumentation-libraries)
    - [ ] Documents all supported configuration parameters.
    - [ ] Documents how to configure manual instrumentation.
    - [x] Documents how to configure log correlation.
    - [ ] Documents minimum supported version of each auto-instrumentation framework.
  - [x] [Real User Monitoring Library](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#real-user-monitoring-libraries)
    - [x] Documents all supported configuration parameters.
    - [x] Documents how to configure manual instrumentation.
    - [x] Documents supported instrumentation.
    - [x] Documents supported platforms.

### How long has the GDI repository been public?

Approximate amount of time

### Is the repository known to be used today?

no

### Is there a date by which this approval is needed?**

no

**Comment by tsloughter-splunk** [comment]
I went through each checklist item in an issue in the ruby repo, https://github.com/signalfx/splunk-otel-ruby/issues/31, since it isn't clear if I should check them off here or if it is for the person reviewing the repo to keep track of I'm leaving them unchecked for now.

**Comment by pellared** [comment]
All issues solved.

**Comment by pellared** [comment]
Ruby distribution is ready for GA!
