### ISSUE TITLE
Deprecate requirement for Jaeger Thrift exporter

### ISSUE THREAD

**Issue by seemk** [signalfx/gdi-specification#190]
With the ingest now supporting OTLP over HTTP, it doesn't make much sense to keep Jaeger Thrift exporter as a required exporter.

Jaeger Client repositories themselves are unmaintained, deprecated and a few of the OpenTelemetry libraries still depend on them (e.g. Node.js). This might produce warnings from vulnerability checks without having a fast way to fix the issues.

The proposal is to lower the wording from `MUST offer` to `MAY offer`.

**Comment by Kielek** [comment]
👍 It will reduce amount of work for Splunj OTel .NET AutoInstrumentation. By default we will have otlp over http probably.

FYI: @signalfx/gdi-dotnet-approvers

**Comment by owais** [comment]
Would be great if it could be dropped but using `"MAY"` **will** lead to conconsist UX across Splunk Otel SDKs. I think we should either drop it from all libs or none. We could opt for dropping it from all but allowing users to install it manually as an additional package if they need.

**Comment by mateuszrzeszutek** [comment]
We could use `MAY offer`, but add an extra condition that the distro MUST mention that this exporter is deprecated; preferably using a log statement.

**Comment by owais** [comment]
The scenario I have in mind is someone instrumenting multiple services written in different languages and being surprised that Jaeger works for one but not for the other. They'd eventually find the deprecation statement in docs but still doesn't eliminate the potentially bad UX. Either way, I'll leave it to actual GDI members to decide and go back into my infra cave :)

**Comment by seemk** [comment]
Agree, ideally I'd strip any mentions to it completely :smile:

**Comment by seemk** [comment]
But this brings in the question that if we are getting rid of parts of the spec, whether we should have guidelines for distro authors when something should give a deprecation warning and when it's OK to remove something completely.

For example with `splunk-otel-js` we want to do a 2.0 release soon, it would be great chance to incorporate breaking changes like this.

**Comment by pellared** [comment]
Personally, I suggest doing it in two phases.

First for GDI spec version 1.x: `MAY offer` + deprecation notice
Second for GDI spec version 2.x: remove it 😉 The instrumentation libraries would have to bump the major version as well.

Side note: As part of spec version 2.x we could also remove `SPLUNK_METRICS_*` env vars in favor of OTel env vars.

**Comment by pellared** [comment]
@seemk Do we want to use this issue to track deprecating `jeager-thrift-splunk` in our distros?

@mzajacsplunk FYI

**Comment by mateuszrzeszutek** [comment]
> @seemk Do we want to use this issue to track deprecating `jeager-thrift-splunk` in our distros?

We could make 1.5 release of the spec, and then distros will just have to implement it to conform to the new version. And then we just close this issue.

**Comment by pellared** [comment]
@MrAlias Are [the issues with milestone 1.5](https://github.com/signalfx/gdi-specification/milestone/4) required for v1.5.0?

**Comment by MrAlias** [comment]
> @MrAlias Are [the issues with milestone 1.5](https://github.com/signalfx/gdi-specification/milestone/4) required for v1.5.0?

They can be bumped to the next release if need be.

**Comment by pellared** [comment]
I will try to create a new release before end of next week and create issues for spec compliance in directly our repositories (e.g. https://github.com/signalfx/splunk-otel-java). Closing this one.
