### ISSUE TITLE
Zipkin exporter vs OTel specification+docs vs GDI docs

### ISSUE THREAD

**Issue by pellared** [signalfx/gdi-specification#197]
I find this requirement awkward:

https://github.com/signalfx/gdi-specification/blob/c9216b2d05faa82da4f5a62d801476994f56ff56/specification/configuration.md#L222-L223

Reasons:

1. We should rather support anything that is "stable" in OTel. Zipkin is a "stable" exporter. See [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#jaeger-exporter)
2. The guidelines regarding documenting "what do we support" are not clear. E.g. if [Zipkin is supported by upstream](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#zipkin-exporter). Does it mean that that Zipkin is supported or not? 

Is this just about "not mentioning" this configuration option in our Splunk docs? If so then I think that in general, we should only describe the configuration options which is important for our distributions (instrumentation libraries). _AFAIK this is what we do anyway._

Maybe we should remove these two lines from the specification to avoid confusion?

**Comment by theletterf** [comment]
Agree with @pellared take on the importance of this. We need to be clear about what we don't support because of efficiency and what we don't support because it's still experimental or deprecated.

**Comment by pellared** [comment]
> we don't support because it's still experimental or deprecated.

Zipkin is "stable" in OTel. As a distribution, I do not think we can say that we do not support something stable from the upstream.

**Comment by mateuszrzeszutek** [comment]
> As a distribution, I do not think we can say that we do not support something stable from the upstream.

On the other hand, we don't want people to use the Zipkin exporter. Perhaps we should add a paragraph of explanation why we're not recommending Zipkin somewhere?
Also, I think we should not remove the `Distribution MUST NOT list Zipkin exporter as supported` line -- I think it adds some value, as we definitely should not list it as a viable option anywhere (even if by accident).

**Comment by pellared** [comment]
Maybe we should simply change the wording (avoid "supported").

How about:

```
- Distribution MUST NOT document the Zipkin exporter (as it not supported by Smart Agent) 
``

**Comment by mateuszrzeszutek** [comment]
Sounds good to me.

**Comment by pjanotti** [comment]
>  Zipkin exporter as supported (not supported by Smart Agent)

I'm surprised by this sentence: the SmartAgent accepted Zipkin. Anyway, there are other good reasons to avoid a Zipkin exporter.

How about instead of listing what "doesn't work" listing the preferred export format OTLP and letting deviations be handled by specific instrumentations? Notice that SFx.NET (not an OTEL fork) uses Zipkin as the only supported export format.

**Comment by theletterf** [comment]
Agree. Omitting stuff we don't want while focusing on the happy path is the way to go :)

Having said that, shall I remove mentions of Zipkin in our docs?

**Comment by mateuszrzeszutek** [comment]
> > Having said that, shall I remove mentions of Zipkin in our docs?
> 
> @theletterf I think that for OTel distros the answer is "yes".

Unless that mention is "don't use Zipkin, use OTLP" 😄

**Comment by theletterf** [comment]
Luckily, we don't mention `Zipkin` in our instrumentation docs (OTel ones), but we do for the Collector. Both the Collector and our backend support Zipkin spans:

- https://docs.splunk.com/Observability/apm/apm-spans-traces/span-formats.html
- https://docs.splunk.com/observability/gdi/opentelemetry/data-processing.html

I believe it's even a default for our Collector distribution.

**Comment by mateuszrzeszutek** [comment]
I think it's understandable for the collector -- we should only produce OTLP (in instrumentation), but accept as much as we can (in collector/ingest)
