### ISSUE TITLE
Add CLA Agreement Tracker integration

### ISSUE THREAD

**Issue by pellared** [signalfx/gdi-specification#236]
GDI repositories should be integrated with https://github.com/splunk/cla-agreement

We should also demonstrate how to do this. It can be even done in this repository and [reused as a composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action).

**Comment by breedx-splk** [comment]
Do we have any other reasonable way right now to verify that external contributors have signed a CLA? Are any signalfx repos doing this yet?

**Comment by pellared** [comment]
> Do we have any other reasonable way right now to verify that external contributors have signed a CLA?

Not any that I am aware of.

> Are any signalfx repos doing this yet?

Not yet. Proposing here https://github.com/signalfx/gdi-specification/pull/268.
PS. This is recommended by our legals (and admins of https://github.com/splunk).
