### ISSUE TITLE
Real User Monitoring configuration naming

### ISSUE THREAD

**Issue by pellared** [signalfx/gdi-specification#246]
From  https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/configuration.md

> Splunk-specific configuration variables defined in the GDI specification MUST be prefixed with SPLUNK_. 

Therefore shouldn't the all configuration like have a `splunk` prefix e.g.
- `rumAccessToken` -> `splunkAccessToken`
- `realm` -> `splunkRealm`

I know that the section is marked as "Stable". But I believe it is still experimental. See https://github.com/signalfx/gdi-specification/pull/247

**Comment by breedx-splk** [comment]
Actually, after another read though I think I disagree with this assertion. This quote:
> Splunk-specific configuration variables defined in the GDI specification MUST be prefixed with SPLUNK_.

...I think was intending to specifically be referring to environment variables. The two RUM items you call out above are NOT injected through the environment, and I think therefore are not subject to the requirement. 

I still think we should keep it stable.

**Comment by pellared** [comment]
Thanks for your feedback. Closing.

**Comment by pellared** [comment]
@t2t2 @seemk What is your opinion on this? Would you prefer to keep the existing configuration naming? Changing it would probably be annoying for the users. On the other hand, the `splunk` prefix can help in differentiating Splunk specific configuration if OTel defines some standards for RUM (Client Instrumentation).

PS. I am fine closing this issue. It is just a double-check.

**Comment by seemk** [comment]
I guess `splunk*` makes more sense, but can just keep the existing one for backwards compatibility.

**Comment by pellared** [comment]
@seemk Do you want to deprecate existing ones (and still support them) and define new ones?

**Comment by t2t2** [comment]
I don't think it makes as much sense, in case of environment variables `SPLUNK_` prefix ensures there's no conflicts with different vendors expecting their own access tokens, while in RUM case all of the configuration parameters are explicitly passed into splunk libraries - following from documentation examples:

```
// Browser
   SplunkRum.init({
      realm: '<realm>',
      rumAccessToken: '<your_rum_token>',

// IOS
SplunkRum.initialize(beaconUrl: "https://rum-ingest.<realm>.signalfx.com/v1/rum",
      rumAuth: "<rum-token>",

// Android
      SplunkRum.builder()
               .setApplicationName("<name_of_app>")
               .setDeploymentEnvironment("<name_of_env>") // Environment
               .setRealm(realm)
               .setRumAccessToken(rumAccessToken)
```

Closest match to environment variables problem would be build-time replacement of variables, eg

```
   SplunkRum.init({
      realm: 'us0',
      rumAccessToken: process.env.REACT_APP_SPLUNK_RUM_ACCESS_TOKEN,
```

But as this passes into developer decisions of how to include the library, it is not relevant

**Comment by pellared** [comment]
Closing.
