### ISSUE TITLE
GA splunk-otel-dotnet

### ISSUE THREAD

**Issue by Kielek** [signalfx/gdi-specification#248]
### Which GDI repository do you wish to GA?

Name and link to repository: Splunk Distribution of OpenTelemetry .NET - https://github.com/signalfx/splunk-otel-dotnet

### Does the repository follow the latest tagged minor release in [GDI specification](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/repository.md)?

- [x] Has an appropriate [maintainers team](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/repository.md#teams).
- [x] [Permissions](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/repository.md#permissions)
      set correctly.
- [x] [Branch protection](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/repository.md#branch-protection)
      in place.
- [x] [Dependencies](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/repository.md#dependencies)
      appropriately locked down.
- [x] [GitHub Applications](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/repository.md#github-applications)
      set up per spec.
- [x] Follows the [configuration requirements](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/configuration.md),
      if appropriate.
- [x] Follows the [semantic convention requirements](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/semantic_conventions.md),
      if appropriate.
- [x] [Required Files](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/repository.md#required-files)
      in place.
  - [x] CHANGELOG.md
  - [x] CODE_OF_CONDUCT.md
  - [x] CONTRIBUTING.md
  - [x] .github/CODEOWNERS
  - [x] LICENSE
  - [x] README.md
    - [x] Build status badge
    - [x] Getting started
    - [x] Troubleshooting
    - [x] Link to official Splunk docs
    - [x] License information
  - [x] SECURITY.md
- [x] [Releases](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/repository.md#github-releases)
      done to spec.
- [x] Type specific requirements
  - [x] [Instrumentation Library](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/repository.md#instrumentation-libraries)
    - [x] Documents all supported configuration parameters.
    - [x] Documents how to configure manual instrumentation.
    - [x] Documents how to configure log correlation.
    - [x] Documents minimum supported version of each auto-instrumentation framework.

### How long has the GDI repository been public?

From the very beginning - first commit: https://github.com/signalfx/splunk-otel-dotnet/commit/805704f44c84228a881c24b1447a953564d5461e

### Is the repository known to be used today?

yes - in the RC phase. It is also documented in O11y documentation.

### Is there a date by which this approval is needed?**

August 21, 2023

### Additional context

Make a official 1.0.0 release of this package.

**Comment by mateuszrzeszutek** [comment]
> * [Permissions](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/repository.md#permissions)
>   set correctly.

The repo does not grant write access to the `signalfx/gdi-specification-approvers`; but then again, no other repo does that (well, I may have not checked all of them). Since it clearly hasn't been needed before, I propose to remove this requirement instead.

**Comment by mateuszrzeszutek** [comment]
> Follows the [configuration requirements](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/configuration.md),
if appropriate.

`SPLUNK_ACCESS_TOKEN` ✅ 
`SPLUNK_REALM ` ✅ 
`SPLUNK_TRACE_RESPONSE_HEADER_ENABLED ` ✅ 
`SPLUNK_PROFILER_*` N/A

`OTEL_SERVICE_NAME` and the missing `service.name` warning ✅ 
`OTEL_PROPAGATORS` ✅ 
Span Collection Limits ❌  does not set unlimited on several properties 
`OTEL_TRACES_EXPORTER` looks like the upstream's using `http/protobuf` ✅

**Comment by mateuszrzeszutek** [comment]
> Follows the [semantic convention requirements](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/semantic_conventions.md),
if appropriate.

`telemetry.sdk.*` ✅ 
`telemetry.auto.version` ✅ 
`process.*` and `process.runtime.*` do not seem to be set anywhere; they're optional so that's fine
`splunk.distro.version` ✅

**Comment by mateuszrzeszutek** [comment]
> .github/CODEOWNERS

CODEOWNERS does not specify `@signalfx/gdi-specification-approvers @signalfx/gdi-specification-maintainers`, but I believe that this is connected to the branch permissions thingy that I mentioned before, and probably actually unneeded. I'll submit a spec fix for that too.

**Comment by mateuszrzeszutek** [comment]
> Releases

> MUST update all examples in the [Splunk OpenTelemetry example repository](https://github.com/signalfx/tracing-examples/tree/main/opentelemetry-tracing) that depends on the repository to use the latest release.

❌  not done https://github.com/signalfx/tracing-examples/blob/f4af470b059b176dbb6767c6f9fb3aee232a42b7/opentelemetry-tracing/opentelemetry-dotnet/automatic/aspnetcore-and-mongodb/InstrumentContainer/Dockerfile#L5

**Comment by mateuszrzeszutek** [comment]
> Type specific requirements
 [Instrumentation Library](https://github.com/signalfx/gdi-specification/blob/v1.5.0/specification/repository.md#instrumentation-libraries)

Documents all supported configuration parameters. -- Splunk docs ✅ 
Documents how to configure manual instrumentation. -- docs ✅ 
Documents how to configure log correlation. ❌ missing, and it looks like the sfx version had that: https://docs.splunk.com/Observability/gdi/get-data-in/application/dotnet/instrumentation/connect-traces-logs.html
Documents minimum supported version of each auto-instrumentation framework. ❌ missing I think? I could not find that in the upstream docs either.

Although, I don't think that the `minimum supported version of each auto-instrumentation framework` docs requirement is well-formed, really; for instance, for Java we only document that in the upstream repo, there's no Splunk documentation on that.

**Comment by mateuszrzeszutek** [comment]
CODEOWNERS and permissions fixed in https://github.com/signalfx/splunk-otel-dotnet/pull/326

**Comment by mateuszrzeszutek** [comment]
Looks like all items have been resolved; I think we're ready to go 🚀
