### ISSUE TITLE
When new minor or major tag is pushed automatically open issue in associated projects

### ISSUE THREAD

**Issue by flands** [signalfx/gdi-specification#63]
**Is your feature request related to a problem? Please describe.**
The GDI specification will cut new releases in the future and GDI project will need to update. This needs to be automated so GDI project maintainers are aware of changes.

**Describe the solution you'd like**
When a minor or major tag is pushed all GDI project following the spec automatically get an issue opened asking to address

**Describe alternatives you've considered**
GDI spec maintainers manually creating these tickets

**Additional context**
This proposal does require keeping state of which GDI projects need to be notified

**Comment by pellared** [comment]
Doing it automatically via GitHub Action would require having a bot account with PAT.

For security reasons, I think it would be better if we prepare a script that could be invoked by GDI spec maintainer as part of the release process.
