### ISSUE TITLE
Configuration of ingest endpoints

### ISSUE THREAD

**Issue by flands** [signalfx/gdi-specification#69]
**Is your feature request related to a problem? Please describe.**
Ability to specify different endpoints for different signals. Especially important as paths may change over time.

**Describe the solution you'd like**
Are we going to specify more specific variables to configure ingest endpoints such as SPLUNK_INGEST_URL (e.g. https://ingest.us0.signalfx.com)? Or maybe even something more specific such as SPLUNK_METRICS_URL (e.g. https://ingest.us0.signalfx.com/v2/datapoint)?

Now the specification mentions only about the SPLUNK_REALM that allows to configure ingesting indirectly.

**Describe alternatives you've considered**
Just using `SPLUNK_REALM`

**Additional context**
#55

**Comment by pellared** [comment]
Closing as `SPLUNK_REALM` seems to be good enough.
