### ISSUE TITLE
Need metric instrumentation library env vars

### ISSUE THREAD

**Issue by flands** [signalfx/gdi-specification#73]
**Is your feature request related to a problem? Please describe.**
Metric supported is being added to OTel distributions ahead of OTel metric support. Configuration needs to be specified to support this use case.

**Describe the solution you'd like**
Decision on how configuration can be done to support:
- Enabling metrics
- Specifying metric destination
- Configuration metrics (at least interval)

**Describe alternatives you've considered**
Currently defined in Java project: https://github.com/signalfx/splunk-otel-java/blob/main/docs/advanced-config.md#splunk-distribution-configuration. Other projects will likely have a similar need.

**Comment by pellared** [comment]
@signalfx/gdi-specification-approvers Is it still needed? I think we can close this one as it looks invalid. We should use OTel metrics now.

**Comment by mateuszrzeszutek** [comment]
> We should use OTel metrics now.

^ this
Long term we don't want any splunk specific config for metrics.

**Comment by pellared** [comment]
I created https://github.com/signalfx/gdi-specification/issues/194. Closing this issue. Anyone can reopen it if needed.
