### ISSUE TITLE
Ease process for setting `service.name`

### ISSUE THREAD

**Issue by MrAlias** [signalfx/gdi-specification#78]
As pointed out in #25, the `service.name` resource attribute is very important for APM. This attribute is what lets APM identify individual services. Today this defaults to `unnamed-<lang>-service` for Splunk libraries. For example, if a user forgets to specify this attribute for a Node service, it'll show up as `unnamed-node-service` in APM. If a user forgets to specify it for multiple node service, then APM will likely treat all of those services as a single service.

Today the only way to specify a value for this attribute is to use the `OTEL_RESOURCE_ATTRIBUTES` environment varariable. For example. `OTEL_RESOURCE_ATTRIBUTES=service.name=svc-payments`. This can be confusing and not obvious for new users. This has been identified in the OTel community and there is an [open issue](https://github.com/open-telemetry/opentelemetry-specification/issues/709) looking to address this.

Ideally the OTel community provides a way to easily set the service name and handles any priority resolution with `OTEL_RESOURCE_ATTRIBUTES` if they add support for an additional environment variable. If this does not happen, and we discover this is a major pain point for customers, we need to add our own environment variable to support this.

### Prior Art

* Old SignalFx libraries had a dedicated config var for service name.
* Lightstep's new Otel distros have dedicated config vars for service name.
* DataDog's new Otel libraries have a dedicated config var for service name. 
* AWS distros don't do anything special and expect the user to configure the attribute via `OTEL_RESOURCE_ATTRS`. 
* Honeycomb uses the `SERVICE_NAME` environment variable that they defined to set this.

**Comment by iNikem** [comment]
@MrAlias https://github.com/open-telemetry/opentelemetry-specification/pull/1677

**Comment by iNikem** [comment]
Spec PR is merge https://github.com/open-telemetry/opentelemetry-specification/pull/1677. We now have `OTEL_SERVICE_NAME`

**Comment by mateuszrzeszutek** [comment]
A bit Java-centric question: should we implement that right now in our javaagent? I suppose that otel SDK will add this in 1.3, but if we're expecting to release splunk-otel-java 1.0 this week it might be a good idea to do it right away in our repo.
CC @jkwatson @flands

**Comment by jkwatson** [comment]
> A bit Java-centric question: should we implement that right now in our javaagent? I suppose that otel SDK will add this in 1.3, but if we're expecting to release splunk-otel-java 1.0 this week it might be a good idea to do it right away in our repo.
> CC @jkwatson @flands

I think we should wait until the spec gets released to put this in. Otherwise, it could get reverted in the spec pre-release and we'd be stuck with having something custom.
