### ISSUE TITLE
Splunk OpenTelemetry Java Lambda Wrapper - GA request

### ISSUE THREAD

**Issue by kubawach** [signalfx/gdi-specification#95]
**Which GDI project do you wish to GA?**
https://github.com/signalfx/splunk-otel-java-lambda

**Does the repository follow the latest tagged minor release in GDI specification?**
yes

**How long has the GDI project been public?**
Four month

**Is the project known to be used today?**
yes

**Is there a date by which this approval is needed?**
no

**Additional context**
Reviewed with all 1.0.0-rc GDI spec parts.
Release process to be changed according to newest Splunk guidelines (not part of the spec, just mentioning).

**Comment by MrAlias** [comment]
Sorry about the delay here. We are prioritizing getting splunk-otel-java released, but this is next in the queue.

**Comment by pellared** [comment]
@mzajacsplunk Can we close this one?

**Comment by pellared** [comment]
@johnbley

**Comment by mateuszrzeszutek** [comment]
Yes, this project is going to be deprecated (in favor of the [Splunk OpenTelemetry Lambda](https://github.com/signalfx/splunk-otel-lambda/)), we don't need to GA it anymore.
